import { ArrowRight } from "lucide-react";
import BackToPreviousPage from "../components/shared/BackToPreviousPage";
import manageTable from "../assets/images/house-committee/manage-table.png";
import referralBrief from "../assets/images/house-committee/referral-brief.png";
import referralDashboard from "../assets/images/house-committee/referral-dashboard.png";
import rosterEdit from "../assets/images/house-committee/roster-edit.png";
import voteTally from "../assets/images/house-committee/vote-tally.png";
import "./house-case-study.css";
import "./house-case-overrides.css";
import "./house-figma-spread.css";
import "./house-six-part.css";
import "./house-product-screens.css";

const facts = [
  ["01 / Context", "0 → 1 product", "A new committee-voting platform for complex legislative workflows."],
  ["02 / Problem", "Fragmented process", "Vote information was collected and displayed inconsistently across committees."],
  ["03 / Users", "Clerks + staff", "Congressional staff and subject-matter experts shaped every workflow decision."],
  ["04 / My role", "UI/UX Designer", "Research, workflow design, interaction design, prototyping, and design specs."],
  ["05 / Delivery", "10 months", "Three weekly working sessions with House leadership, live prototypes, and demos."],
  ["06 / Evidence", "30+ components", "Reusable USWDS patterns documented for implementation and future work."],
];

export default function HouseCaseStudy() {
  return <main className="case-study">
    <section className="case-hero">
      <div className="case-hero__bar"><BackToPreviousPage /><span>U.S. House / Committee voting platform / TL;DR</span></div>
      <div className="case-hero__layout">
        <aside className="case-hero__intro"><p className="case-kicker">01 &nbsp; The TL;DR <b>✦</b></p><h1>Modernizing legislative workflows <em>for the web.</em></h1><p>A 0→1 committee-voting platform for the U.S. House of Representatives—bringing referrals, member rosters, and roll-call voting into one clear, accessible workflow.</p><a href="#story">20-second read <ArrowRight size={15}/></a></aside>
        <div className="case-anatomy case-anatomy--real" aria-label="Anatomy of the House Committee voting platform">
          <p className="case-anatomy__eyebrow">Anatomy of the project <span>— pull apart to understand</span></p>
          <div className="case-screen case-screen--nav case-screen--nav-image"><img src={referralDashboard} alt="Committee Referrals dashboard navigation" /></div>
          <div className="case-screen case-screen--image"><small>01 / Find the work</small><img src={manageTable} alt="Committee Referrals dashboard with filters and Manage Table settings" /></div>
          <div className="case-screen case-screen--image"><small>02 / Understand the context</small><img src={referralBrief} alt="Referral Brief contextual detail panel" /></div>
          <div className="case-screen case-screen--image"><small>03 / Act with confidence</small><img src={voteTally} alt="Roll Call Vote tally interface" /></div>
          <div className="case-screen case-screen--short case-screen--image"><small>04 / Maintain the system</small><img src={rosterEdit} alt="Committee roster editing interface" /></div>
        </div>
        <div className="case-facts">{facts.map(([eyebrow,title,copy])=><article key={title}><p>{eyebrow}</p><h2>{title}</h2><span>{copy}</span></article>)}</div>
      </div>
    </section>
    <section id="story" className="case-story"><p className="case-kicker">02 &nbsp; The story <b>✦</b></p><div><h2>A platform built around how committee work actually moves.</h2><p>The existing process had no modern, unified way to collect and display committee-vote information. I partnered with House leadership three times a week, then conducted approximately 18 interviews across two research rounds with congressional staff and subject-matter experts. Findings became high-fidelity prototypes, live demos, user stories, acceptance criteria, and implementation-ready patterns in Figma and Azure DevOps.</p></div><div className="case-story__tiles"><article><img className="case-workflow-screen" src={referralBrief} alt="Referral Brief panel shown in the Committee Referrals workflow"/><span>01</span><h3>Referral context</h3><p>Briefs keep bill status, sponsors, cosponsors, and referral history inside the workflow so staff can make informed decisions without losing their place.</p></article><article><img className="case-workflow-screen" src={rosterEdit} alt="Committee roster editing interface for majority and minority representatives"/><span>02</span><h3>Roster management</h3><p>A structured, editable view supports committee clerks and staff in maintaining the official record of majority and minority members.</p></article><article><img className="case-workflow-screen" src={voteTally} alt="Roll Call Vote panel with a tally and representative voting controls"/><span>03</span><h3>Voting workflow</h3><p>Complex voting requirements became a clear, traceable sequence while preserving the legislative rules and public-record responsibilities behind them.</p></article></div></section>
    <section className="case-figma-spread"><div className="case-figma-spread__intro"><p className="case-kicker">03 &nbsp; The system <b>✦</b></p><h2>A shared USWDS language for committee work.</h2><p>The product needed more than individual screens. It needed a reliable system that could support multiple modules, changing legislative activity, and future implementation work without creating a new experience every time a feature was added.</p><p>Using USWDS principles as a foundation, I created more than 30 reusable components and patterns for search, filters, tables, status indicators, referral details, forms, voting controls, and administrative actions.</p></div><div className="case-design-board" aria-label="Design system composition"><div className="case-design-board__bar"><span>House Committee Design System</span><span>Components + patterns</span></div><div className="case-design-board__tokens"><span/><span/><span/><span/><span/></div><div className="case-design-board__components"><article className="case-component"><b>Filters + status</b><div/></article><article className="case-component"><b>Voting forms</b><div/></article><article className="case-component case-component--table"><b>Committee referrals</b><div/></article></div></div></section>
    <section className="case-chapter case-chapter--insights"><p className="case-kicker">04 &nbsp; What I learned <b>✦</b></p><h2>Clarity comes from keeping context close.</h2><p className="case-chapter__intro">The challenge was not reducing legislative complexity. It was designing an experience that could hold that complexity without making staff work harder to understand it.</p><div className="case-insight-grid"><article><b>Context can’t disappear.</b><p>Staff need relevant legislative information while they are actively completing work—not somewhere else to search for and remember. The Referral Brief keeps critical context within the task.</p></article><article><b>Complex does not have to mean complicated.</b><p>Voting requirements contain real rules and exceptions. Progressive disclosure organized those details into understandable choices without oversimplifying the work.</p></article><article><b>Findability comes before action.</b><p>Before acting, staff need to locate the correct bill, understand its status, and trust the information they are seeing. Search, filters, and hierarchy establish that confidence.</p></article></div></section>
    <section className="case-chapter case-chapter--decisions"><p className="case-kicker">05 &nbsp; Decisions that shaped the product <b>✦</b></p><h2>Every decision reduced unnecessary complexity.</h2><p className="case-chapter__intro">Research, live prototype reviews, and close collaboration with House staff informed a product that is clear without removing the information legislative work requires.</p><div className="case-decision-grid"><article><span>01 / Structure</span><h3>Turn a long workflow into clear stages.</h3><p>Locating a referral, reviewing context, maintaining the committee roster, recording a vote, and documenting an outcome each have their own focused module—while still belonging to one coherent process.</p></article><article><span>02 / Context</span><h3>Keep information where decisions happen.</h3><p>The Referral Brief brings relevant bill details, sponsor information, cosponsors, and referral history closer to the point of action, reducing unnecessary navigation.</p></article><article><span>03 / Navigation</span><h3>Create one source of truth.</h3><p>The Committee Referrals dashboard combines search, filters, tables, and status patterns so staff can locate and manage legislative activity without relying on disconnected sources.</p></article></div></section>
    <section className="case-chapter case-chapter--outcome"><p className="case-kicker">06 &nbsp; Outcome + reflection <b>✦</b></p><div className="case-outcome"><div><h2>Built for real legislative work.</h2><p>The House Committee Votes Portal moved from a fragmented process toward a shared digital foundation for referrals, roster management, and voting. Recurring leadership sessions, two research rounds, live prototype reviews, and implementation alignment gave the team more than screens: a clearer model of the work and a reusable system for extending it.</p><div className="case-outcome__impact"><p><b>People</b> — clearer pathways for staff to locate work, review context, manage committee information, and complete voting tasks.</p><p><b>Product</b> — a coherent workflow for referrals, rosters, and roll-call voting.</p><p><b>System</b> — reusable components, documented patterns, and implementation-ready guidance for future work.</p></div></div><div className="case-outcome__quote">“Complex systems don’t become usable simply by removing information. Clarity comes from understanding which information someone needs, when they need it, and how the pieces fit together.”<span>My role was not to make legislative work simple. It was to make its complexity navigable.</span></div></div></section>
  </main>;
}
