// Generates hand-drawn constellation linework from real star positions.
// Output: fixed SVG path data (seeded, so it is identical every run).
import fs from 'fs';

let seed = 1121;
const rand = () => (seed = (seed * 16807) % 2147483647) / 2147483647;
const r1 = (n) => Math.round(n * 10) / 10;

// [ra hours, dec degrees, magnitude, name?]
const SCO = {
  beta: [16.091, -19.81, 2.6], delta: [16.006, -22.62, 2.3], pi: [15.981, -26.11, 2.9], rho: [15.948, -29.21, 3.9],
  sigma: [16.353, -25.59, 2.9], alpha: [16.490, -26.43, 0.9, 'Antares'], tau: [16.598, -28.22, 2.8], epsilon: [16.836, -34.29, 2.3],
  mu: [16.864, -38.05, 3.0], zeta: [16.910, -42.36, 3.6], eta: [17.203, -43.24, 3.3], theta: [17.622, -43.00, 1.9],
  iota: [17.793, -40.13, 3.0], kappa: [17.708, -39.03, 2.4], lambda: [17.560, -37.10, 1.6], upsilon: [17.513, -37.30, 2.7],
};
const SCO_LINES = [['beta', 'delta', 'pi', 'rho'], ['delta', 'sigma', 'alpha', 'tau', 'epsilon', 'mu', 'zeta', 'eta', 'theta', 'iota', 'kappa', 'lambda', 'upsilon']];

// Aquarius: only the Water Jar (gamma, zeta, eta, pi) plus Sadalmelik, the part that survives simplifying
const AQR = {
  alpha: [22.096, -0.32, 3.0], gamma: [22.361, -1.39, 3.8], zeta: [22.481, -0.02, 3.6], eta: [22.589, -0.12, 4.0], pi: [22.421, 1.38, 4.6],
};
const AQR_LINES = [['alpha', 'gamma', 'zeta', 'eta'], ['gamma', 'pi']];

// project to a box; rotate degrees (0 keeps the true sky orientation)
function project(stars, w, h, rotate, pad) {
  const ras = Object.values(stars).map((s) => s[0]);
  const ra0 = (Math.min(...ras) + Math.max(...ras)) / 2;
  const pts = Object.fromEntries(Object.entries(stars).map(([k, [ra, dec]]) => {
    // offsets from the figure's centre; sky charts put east on the left, so x grows as RA falls
    const x = -(ra - ra0) * 15 * Math.cos((dec * Math.PI) / 180), y = -dec;
    const a = (rotate * Math.PI) / 180;
    return [k, [x * Math.cos(a) - y * Math.sin(a), x * Math.sin(a) + y * Math.cos(a)]];
  }));
  const xs = Object.values(pts).map((p) => p[0]), ys = Object.values(pts).map((p) => p[1]);
  const [x0, x1, y0, y1] = [Math.min(...xs), Math.max(...xs), Math.min(...ys), Math.max(...ys)];
  const s = Math.min((w - pad * 2) / (x1 - x0), (h - pad * 2) / (y1 - y0));
  const ox = (w - (x1 - x0) * s) / 2, oy = (h - (y1 - y0) * s) / 2;
  for (const k in pts) pts[k] = [ox + (pts[k][0] - x0) * s, oy + (pts[k][1] - y0) * s];
  return pts;
}

// one hand-drawn segment: starts and stops short of each star, bows slightly, wobbles a touch
function inkSegment(a, b, gap) {
  const dx = b[0] - a[0], dy = b[1] - a[1], len = Math.hypot(dx, dy);
  const ux = dx / len, uy = dy / len, nx = -uy, ny = ux;
  const s = [a[0] + ux * gap, a[1] + uy * gap], e = [b[0] - ux * gap, b[1] - uy * gap];
  const bow = (rand() - 0.5) * Math.min(5, len * 0.05);
  const c1 = [s[0] + (e[0] - s[0]) * 0.33 + nx * (bow + (rand() - 0.5) * 1.2), s[1] + (e[1] - s[1]) * 0.33 + ny * (bow + (rand() - 0.5) * 1.2)];
  const c2 = [s[0] + (e[0] - s[0]) * 0.66 + nx * (bow * 0.8 + (rand() - 0.5) * 1.2), s[1] + (e[1] - s[1]) * 0.66 + ny * (bow * 0.8 + (rand() - 0.5) * 1.2)];
  return `M${r1(s[0])} ${r1(s[1])}C${r1(c1[0])} ${r1(c1[1])} ${r1(c2[0])} ${r1(c2[1])} ${r1(e[0])} ${r1(e[1])}`;
}

function build(stars, lines, w, h, rotate, pad) {
  const p = project(stars, w, h, rotate, pad);
  const segments = [];
  for (const path of lines) for (let i = 0; i < path.length - 1; i++) segments.push(inkSegment(p[path[i]], p[path[i + 1]], 5));
  const marks = Object.entries(stars).map(([k, [, , mag, name]]) => ({ k, x: r1(p[k][0]), y: r1(p[k][1]), r: r1(Math.max(1.3, 4 - mag * 0.75)), name: name || null }));
  return { w, h, segments, marks };
}

const out = {
  scorpius: build(SCO, SCO_LINES, 300, 220, 0, 14),
  aquarius: build(AQR, AQR_LINES, 120, 90, 0, 12),
};
fs.writeFileSync(process.argv[2], `// Generated by scripts/constellations.mjs from real star positions. Do not edit by hand.\nexport const CONSTELLATIONS = ${JSON.stringify(out, null, 2)};\n`);
console.log('scorpius', out.scorpius.segments.length, 'segments; aquarius', out.aquarius.segments.length);
