// Copies the icons this site uses out of the open-source sets into
// src/components/shared/icons/iconData.js, so no icon library ships at
// runtime. Run with the two Iconify JSON packages installed:
//   npm i --no-save @iconify-json/guidance @iconify-json/logos
//   node scripts/icons.mjs
// Guidance by Streamline is CC BY 4.0 (credited in the footer).
// Logos by Gil Barbara are CC0.
import fs from 'fs';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const guidance = require('@iconify-json/guidance/icons.json');
const logos = require('@iconify-json/logos/icons.json');

// name on this site -> name in the Guidance set
const LINE = {
  discover: 'search', define: 'map', design: 'pen', develop: 'tools', deliver: 'send',
  professional: 'paper', studio: 'tickets', uikit: 'ui-phone',
  culture: 'projection-room', remote: 'globe',
  mail: 'mail', close: 'remove-x-cross', play: 'play', star: 'star',
  // the set names its arrows from the arrowhead's side; these are checked by eye
  'arrow-up-right': 'up-right-arrow', 'arrow-left': 'right-arrow', 'arrow-right': 'left-arrow',
  'arrow-up': 'up-arrow', 'arrow-down': 'down-arrow',
};
const BRAND = { linkedin: 'linkedin-icon', pinterest: 'pinterest', github: 'github-icon' };

const pick = (set, name) => {
  const icon = set.icons[name];
  if (!icon) throw new Error(`missing icon: ${name}`);
  return { body: icon.body, width: icon.width || set.width || 24, height: icon.height || set.height || 24 };
};
const line = Object.fromEntries(Object.entries(LINE).map(([k, v]) => [k, pick(guidance, v)]));
const brand = Object.fromEntries(Object.entries(BRAND).map(([k, v]) => [k, pick(logos, v)]));

fs.writeFileSync('src/components/shared/icons/iconData.js', `// Generated by scripts/icons.mjs. Do not edit by hand.
// Line icons: Guidance by Streamline, CC BY 4.0. Brand logos: Gil Barbara's logos, CC0.
export const LINE_ICONS = ${JSON.stringify(line, null, 2)};
export const BRAND_ICONS = ${JSON.stringify(brand, null, 2)};
`);
console.log(Object.keys(line).length, 'line icons,', Object.keys(brand).length, 'brand logos');
